// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

@ffi.Native<
  ffi.Pointer<llama_dart_handle> Function(
    ffi.Pointer<ffi.Char>,
    ffi.Int32,
    ffi.Int32,
  )
>()
external ffi.Pointer<llama_dart_handle> llama_dart_create(
  ffi.Pointer<ffi.Char> model_path,
  int n_ctx,
  int n_threads,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<llama_dart_handle>)>()
external void llama_dart_destroy(ffi.Pointer<llama_dart_handle> handle);

@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<llama_dart_handle>,
    ffi.Pointer<ffi.Char>,
    ffi.Int32,
    ffi.Pointer<ffi.Char>,
    ffi.Int32,
  )
>()
external int llama_dart_generate(
  ffi.Pointer<llama_dart_handle> handle,
  ffi.Pointer<ffi.Char> prompt,
  int max_tokens,
  ffi.Pointer<ffi.Char> out_buf,
  int out_buf_len,
);

final class llama_dart_handle extends ffi.Opaque {}
